#mybatis
mybatis:
  type-aliases-package: com.lanou.model
  mapper-locations: classpath:mappers/*.xml

#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.lanou.util.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

page: 5